server:
  port: ${PORT:5000}
  profiles:
    active: default
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://t7r3fe9ul3o1hem9:x4sqq2z2ncmfxbsf@x8autxobia7sgh74.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/yccxahytx1khyf52
    #    username: t7r3fe9ul3o1hem9
    #    password: x4sqq2z2ncmfxbsf
    url: jdbc:mysql://localhost:3306/kotlin?serverTimezone=Asia/Seoul
    username: usan
    password: dgdg1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  messages:
    basename: errors